language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: S/mczXnJr7/npCyMZmv0TAN5R8m8II/EcOg8OVpsgH80e6+Wnz+A9X7k+TeXmcLcQo9GqjPr36fDwvrmbVHuzjiPFYYmXIrKPQ6NyC3Wh4AnJZU7VSLL2SFEEDSRmbENsmJnUsNEYEWevVQyS323mB+sdeVj2sD+AVIKYsJ27VM5kXfnNAsBrQLNBFIQb9YkrHJTSTgpAB3+KqfzArB3JwKIyTBM49xtSEaF0ep9V5rtKQqxph/j9XaRsQEf+2a9n3nIELPFMJKrecvsfD1IL67pH03SIgBvzleplxAodpWCWdOas+9C2vJ3YhEQsCNsOiJDdJtfugkASneCYK+SIHMKrIeSMDaO/zL/0zvTmBmgcTtpsVbFgK7bwSjxECMS4iVIy5LtxPdis0f4Cvz1DXfDvsgZrxdJ/fNWeAIlRJGSgERmDT48XsbOX4ORWZReaCKRe43VpVOPcIV20CkKz22ZdLggU+RQaf2ngW2cGc0hY/EetUJM4jLOfadWz/ILcWQ9+43sT4pob7VLz13ABXn5HmmUr7YeQ60wIR49Ss5QeJPLOE1nSIM9n3UP1TcAOGk8DnqxuAZ+OMA/AF5ZxSbfg6Y2pW8KyycAFTyeDgKxM1c2SsZw7t9bBXB59qumKODY0Fybtnwh4clP6anyXD59Owba2xIS0SLYjLcKviU=
  file:
    - "unist-util-find-after.js"
    - "unist-util-find-after.min.js"
  on:
    tags: true
